import { Inter } from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Bootstrap from "./(Components)/Bootstrap";
import "./globals.css";
import Navbar from "./(Components)/Navbar/Navbar";
import Footer from "./Footer/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Bootstrap />
        <Footer></Footer>
      </body>
    </html>
  );
}
